server:
  port: 8080

spring:
  application:
    name: sst-project
  datasource:
    url: 'jdbc:postgresql://localhost/postgres?currentSchema=public'
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

restClient:
  url: "http://localhost:8081/api/"